.TH ZORK2 6 "August 2026" "Zork II" "Games Manual"
.SH NAME
zork2 \- play Zork II: The Wizard of Frobozz
.SH SYNOPSIS
.B zork2
.RI [ frotz-options ]
.SH DESCRIPTION
.B zork2
starts Zork II using the Frotz Z-machine interpreter.
The game is an interactive-fiction adventure controlled by typed commands.
.PP
The packaged story file is installed at
.IR /usr/share/games/zork2/zork2.z3 .
.SH OPTIONS
Options are passed directly to
.BR frotz (6)
before the story-file argument.
.SH FILES
.TP
.I /usr/share/games/zork2/zork2.z3
Z-machine version 3 story image supplied by upstream.
.SH SEE ALSO
.BR frotz (6),
.BR dfrotz (6)
.SH HOMEPAGE
https://github.com/historicalsource/zork2
